In [1]:
import tensorflow as tf 
from tensorflow.keras.preprocessing.text import one_hot


2024-10-03 08:46:43.160744: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-10-03 08:46:43.161274: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-10-03 08:46:43.164288: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-10-03 08:46:43.171713: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-10-03 08:46:43.185744: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been 

In [2]:
sent = [
    'The quick brown fox jumps over the lazy dog',
    'I love my dog',
    'She loves her cat',
    'They are playing outside',
    'The cat is sleeping',
    'The dog is barking',
    'I am hungry',
    'She is thirsty',
    'They are tired',
    'The cat is playing with the mouse',
    'The dog is eating',
]

In [3]:
voc_size = 10000

In [4]:
one_hot_repr = [one_hot(words, voc_size) for words in sent]

In [5]:
one_hot_repr

[[9774, 1396, 9338, 6281, 4693, 6295, 9774, 3545, 8707],
 [5432, 9768, 1776, 8707],
 [8372, 6395, 8663, 9814],
 [3329, 4702, 1992, 666],
 [9774, 9814, 1605, 8532],
 [9774, 8707, 1605, 8051],
 [5432, 7661, 5266],
 [8372, 1605, 937],
 [3329, 4702, 3450],
 [9774, 9814, 1605, 1992, 9882, 9774, 5158],
 [9774, 8707, 1605, 6356]]

In [6]:
#Word embedding representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [7]:
#making all sentences of the same size
sent_length = 10
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)

In [8]:
embedded_docs

array([[   0, 9774, 1396, 9338, 6281, 4693, 6295, 9774, 3545, 8707],
       [   0,    0,    0,    0,    0,    0, 5432, 9768, 1776, 8707],
       [   0,    0,    0,    0,    0,    0, 8372, 6395, 8663, 9814],
       [   0,    0,    0,    0,    0,    0, 3329, 4702, 1992,  666],
       [   0,    0,    0,    0,    0,    0, 9774, 9814, 1605, 8532],
       [   0,    0,    0,    0,    0,    0, 9774, 8707, 1605, 8051],
       [   0,    0,    0,    0,    0,    0,    0, 5432, 7661, 5266],
       [   0,    0,    0,    0,    0,    0,    0, 8372, 1605,  937],
       [   0,    0,    0,    0,    0,    0,    0, 3329, 4702, 3450],
       [   0,    0,    0, 9774, 9814, 1605, 1992, 9882, 9774, 5158],
       [   0,    0,    0,    0,    0,    0, 9774, 8707, 1605, 6356]],
      dtype=int32)

In [9]:
#Feature representation 
dim = 10


In [12]:


from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Embedding

# Define the input
inputs = Input(shape=(sent_length,))  # Input shape should match the sentence length

# Embedding layer
x = Embedding(voc_size, dim, input_length=sent_length)(inputs)

# Create the model
model = Model(inputs=inputs, outputs=x)

# Compile the model with optimizer, loss, and metrics
model.compile(optimizer='adam', loss='mse', metrics=['accuracy'])

# Display the model summary
model.summary()


Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)        │ (None, 10)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ embedding_1 (Embedding)         │ (None, 10, 10)         │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [13]:
model.summary()

Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)        │ (None, 10)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ embedding_1 (Embedding)         │ (None, 10, 10)         │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [14]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step


array([[[ 0.04501564, -0.03353045, -0.0398403 , ..., -0.01543595,
         -0.04326865, -0.01846619],
        [ 0.00202153, -0.00067431,  0.03110835, ..., -0.02173481,
          0.03276492,  0.01647422],
        [-0.03778998,  0.01628229,  0.01894705, ..., -0.00998114,
         -0.04115205, -0.00860079],
        ...,
        [ 0.00202153, -0.00067431,  0.03110835, ..., -0.02173481,
          0.03276492,  0.01647422],
        [ 0.04140585, -0.04565802,  0.00689939, ..., -0.03599383,
         -0.03492529, -0.02338375],
        [ 0.01073635,  0.00340978,  0.01747953, ..., -0.02371273,
          0.03235004, -0.04734092]],

       [[ 0.04501564, -0.03353045, -0.0398403 , ..., -0.01543595,
         -0.04326865, -0.01846619],
        [ 0.04501564, -0.03353045, -0.0398403 , ..., -0.01543595,
         -0.04326865, -0.01846619],
        [ 0.04501564, -0.03353045, -0.0398403 , ..., -0.01543595,
         -0.04326865, -0.01846619],
        ...,
        [-0.0178171 ,  0.04796917,  0.04112582, ...,  

In [15]:
embedded_docs[0]

array([   0, 9774, 1396, 9338, 6281, 4693, 6295, 9774, 3545, 8707],
      dtype=int32)