In [5]:
import tensorflow as tf 
from tensorflow.keras.preprocessing.text import one_hot


In [2]:
sent = [
    'The quick brown fox jumps over the lazy dog',
    'I love my dog',
    'She loves her cat',
    'They are playing outside',
    'The cat is sleeping',
    'The dog is barking',
    'I am hungry',
    'She is thirsty',
    'They are tired',
    'The cat is playing with the mouse',
    'The dog is eating',
]

In [3]:
voc_size = 10000

In [6]:
one_hot_repr = [one_hot(words, voc_size) for words in sent]

In [7]:
one_hot_repr

[[2980, 9125, 5263, 2064, 9414, 1414, 2980, 9287, 4992],
 [8114, 1357, 609, 4992],
 [493, 3379, 4967, 5165],
 [2964, 6750, 9046, 4899],
 [2980, 5165, 637, 5006],
 [2980, 4992, 637, 3301],
 [8114, 1211, 3252],
 [493, 637, 9647],
 [2964, 6750, 8002],
 [2980, 5165, 637, 9046, 5647, 2980, 3776],
 [2980, 4992, 637, 8131]]

In [8]:
#Word embedding representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [9]:
#making all sentences of the same size
sent_length = 10
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)

In [10]:
embedded_docs

array([[   0, 2980, 9125, 5263, 2064, 9414, 1414, 2980, 9287, 4992],
       [   0,    0,    0,    0,    0,    0, 8114, 1357,  609, 4992],
       [   0,    0,    0,    0,    0,    0,  493, 3379, 4967, 5165],
       [   0,    0,    0,    0,    0,    0, 2964, 6750, 9046, 4899],
       [   0,    0,    0,    0,    0,    0, 2980, 5165,  637, 5006],
       [   0,    0,    0,    0,    0,    0, 2980, 4992,  637, 3301],
       [   0,    0,    0,    0,    0,    0,    0, 8114, 1211, 3252],
       [   0,    0,    0,    0,    0,    0,    0,  493,  637, 9647],
       [   0,    0,    0,    0,    0,    0,    0, 2964, 6750, 8002],
       [   0,    0,    0, 2980, 5165,  637, 9046, 5647, 2980, 3776],
       [   0,    0,    0,    0,    0,    0, 2980, 4992,  637, 8131]],
      dtype=int32)

In [11]:
#Feature representation 
dim = 10


In [12]:
model = Sequential()
model.add(Embedding(voc_size, dim, input_length=sent_length))
model.compile('adam', loss='mse', metrics=['accuracy'])

/home/sikander/miniconda3/lib/python3.12/site-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [13]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [14]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step


array([[[ 0.03080307, -0.03068882, -0.00275769, ...,  0.0107101 ,
         -0.00993683,  0.0439388 ],
        [ 0.00275306, -0.02616031,  0.0414212 , ..., -0.03258442,
         -0.04290713, -0.0145017 ],
        [-0.00601779,  0.0250091 , -0.02717233, ...,  0.00896237,
         -0.04629177,  0.00391597],
        ...,
        [ 0.00275306, -0.02616031,  0.0414212 , ..., -0.03258442,
         -0.04290713, -0.0145017 ],
        [-0.04055967, -0.0439168 ,  0.02290999, ..., -0.03330393,
         -0.04838402, -0.01727171],
        [ 0.03480877,  0.02061708,  0.00756855, ..., -0.02740966,
         -0.02436264,  0.0357289 ]],

       [[ 0.03080307, -0.03068882, -0.00275769, ...,  0.0107101 ,
         -0.00993683,  0.0439388 ],
        [ 0.03080307, -0.03068882, -0.00275769, ...,  0.0107101 ,
         -0.00993683,  0.0439388 ],
        [ 0.03080307, -0.03068882, -0.00275769, ...,  0.0107101 ,
         -0.00993683,  0.0439388 ],
        ...,
        [ 0.04531444, -0.04743056,  0.02996648, ..., -

In [15]:
embedded_docs[0]

array([   0, 2980, 9125, 5263, 2064, 9414, 1414, 2980, 9287, 4992],
      dtype=int32)